theme: minima
email: tianyu.cui@uconn.edu
description: Welcome to my personal web site!

header_pages:
    - about.md
    - research.md
    - gallery.md
    - blogs.md
    - contact.md

twitter_username: Tian_Yu_Cui
